// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TPV_Sistema.Migrations
{
    [DbContext(typeof(ElkarteaDbContext))]
    [Migration("20251110190952_DatuBaseZuzendua")]
    partial class DatuBaseZuzendua
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TPV_Sistema.Models.Erabiltzailea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErabiltzaileIzena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pasahitza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Erabiltzaileak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Erreserba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErabiltzaileaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MahaiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Otordua")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ErabiltzaileaId");

                    b.HasIndex("MahaiaId");

                    b.ToTable("Erreserbak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Eskaera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErabiltzaileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErabiltzaileaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Guztira")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProduktuaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ErabiltzaileaId");

                    b.HasIndex("ProduktuaId");

                    b.ToTable("Eskaerak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.EskaeraLerroa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EskaeraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kantitatea")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrezioaUnitateko")
                        .HasColumnType("REAL");

                    b.Property<int>("ProduktuaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EskaeraId");

                    b.HasIndex("ProduktuaId");

                    b.ToTable("EskaeraLerroak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Mahaia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edukiera")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MahaiIzena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mahaiak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Produktua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prezioa")
                        .HasColumnType("REAL");

                    b.Property<int>("Stocka")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produktuak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Erreserba", b =>
                {
                    b.HasOne("TPV_Sistema.Models.Erabiltzailea", "Erabiltzailea")
                        .WithMany("Erreserbak")
                        .HasForeignKey("ErabiltzaileaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPV_Sistema.Models.Mahaia", "Mahaia")
                        .WithMany("Erreserbak")
                        .HasForeignKey("MahaiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Erabiltzailea");

                    b.Navigation("Mahaia");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Eskaera", b =>
                {
                    b.HasOne("TPV_Sistema.Models.Erabiltzailea", "Erabiltzailea")
                        .WithMany("Eskaerak")
                        .HasForeignKey("ErabiltzaileaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPV_Sistema.Models.Produktua", null)
                        .WithMany("EskaeraLerroak")
                        .HasForeignKey("ProduktuaId");

                    b.Navigation("Erabiltzailea");
                });

            modelBuilder.Entity("TPV_Sistema.Models.EskaeraLerroa", b =>
                {
                    b.HasOne("TPV_Sistema.Models.Eskaera", "Eskaera")
                        .WithMany("Lerroak")
                        .HasForeignKey("EskaeraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPV_Sistema.Models.Produktua", "Produktua")
                        .WithMany()
                        .HasForeignKey("ProduktuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eskaera");

                    b.Navigation("Produktua");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Erabiltzailea", b =>
                {
                    b.Navigation("Erreserbak");

                    b.Navigation("Eskaerak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Eskaera", b =>
                {
                    b.Navigation("Lerroak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Mahaia", b =>
                {
                    b.Navigation("Erreserbak");
                });

            modelBuilder.Entity("TPV_Sistema.Models.Produktua", b =>
                {
                    b.Navigation("EskaeraLerroak");
                });
#pragma warning restore 612, 618
        }
    }
}
